name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-repository-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-repository-
      - name: Build with Maven
        run: mvn -f pom.xml -B clean verify
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: target/tokenreplacer-*-distribution.zip
